local _, L = ...; 
local LOCALE = GetLocale()

if LOCALE == "enUS" then
	-- The EU English game client also
	-- uses the US English locale code.
	--BloodlustMusicConfig.lua
	L[" is now set to: "] = " is now set to: "
	L[" soundchannel during Hero"] = " soundchannel during Hero"
	L[" volume during Hero"] = " volume during Hero"
	L["'|r will play: "] = "'|r will play: "
	L["'|r\n becomes \n|cFFFFD100'"] = "'|r\n becomes \n|cFFFFD100'"
	L["'|r\n turns back to \n|cFFFFD100'"] = "'|r\n turns back to \n|cFFFFD100'"
	L["'|r\n \n \n Accept and reload?"] = "'|r\n \n \n Accept and reload?"
	L["A stupid Addon to play music during Hero, Bloodlust, Primal Rage, etc. You can change a couple of settings below to your liking. Some barebones information is provided next to the corresponding option. For a more in depth explanation, please refer to the description of the addon at: https://www.curseforge.com/wow/addons/bloodlustmusic . Thanks and enjoy!"] = "A stupid Addon to play music during Hero, Bloodlust, Primal Rage, etc. You can change a couple of settings below to your liking. Some barebones information is provided next to the corresponding option. For a more in depth explanation, please refer to the description of the addon at: https://www.curseforge.com/wow/addons/bloodlustmusic . Thanks and enjoy!"
	L["Accept"] = "Accept"
	L["Bloodlust Music"] = "Bloodlust Music"
	L["Cancel"] = "Cancel"
	L["Change Song filename to: \n |cFFFFD100(NB: Needs filetype in the name, .ogg is most common. Also make sure the file for any custom song is in the 'customsongs' folder, not the 'sounds' folder)|r"] = "Change Song filename to: \n |cFFFFD100(NB: Needs filetype in the name, .ogg is most common. Also make sure the file for any custom song is in the 'customsongs' folder, not the 'sounds' folder)|r"
	L["Change Title to: "] = "Change Title to: "
	L["Changing soundchannel prevented, please do so after hero has ended"] = "Changing soundchannel prevented, please do so after hero has ended"
	L["Clear Favored Friend List"] = "Clear Favored Friend List"
	L["Current soundchannel: "] = "Current soundchannel: "
	L["Edit"] = "Edit"
	L["Everything set? Press the button below for a 10 second test song. Enter a number between 1 and 60 to test a specific song. Want a random one? Leave it empty or place a 0. Please note: no other songs can play at the same time."] = "Everything set? Press the button below for a 10 second test song. Enter a number between 1 and 60 to test a specific song. Want a random one? Leave it empty or place a 0. Please note: no other songs can play at the same time."
	L["Favored Friend filename: \n |cFFFFD100(NB: Needs filetype in the name, .ogg is most common. Also make sure the file for any custom song is in the 'customsongs' folder, not the 'sounds' folder)|r"] = "Favored Friend filename: \n |cFFFFD100(NB: Needs filetype in the name, .ogg is most common. Also make sure the file for any custom song is in the 'customsongs' folder, not the 'sounds' folder)|r"
	L["Favored Friend Name: "] = "Favored Friend Name: "
	L["Favored Friend Song Title: "] = "Favored Friend Song Title: "
	L["|cFFFFD100Mute|r"] = "|cFFFFD100Mute|r"
	L["Pending changes: \n \n \n|cFFFFD100'"] = "Pending changes: \n \n \n|cFFFFD100'"
	L["Play a test song"] = "Play a test song"
	L["Regular volume level for "] = "Regular volume level for "
	L["Reset to Default"] = "Reset to Default"
	L["Resetting prevented, please try again after Hero has ended"] = "Resetting prevented, please try again after Hero has ended"
	L["Set all songs to default"] = "Set all songs to default"
	L["Set Max number of soundchannels during Hero to 128?"] = "Set Max number of soundchannels during Hero to 128?"
	L["Sometimes the music will cut out if stuff gets too busy. You can try to prevent this by checking the box below. This will make sure WoW can play more sounds at the same time, by upping the number of allowed soundchannels. Afterwards it will put it back to normal levels. Highly recommended to check the addon description for more info."] = "Sometimes the music will cut out if stuff gets too busy. You can try to prevent this by checking the box below. This will make sure WoW can play more sounds at the same time, by upping the number of allowed soundchannels. Afterwards it will put it back to normal levels. Highly recommended to check the addon description for more info."
	L["Song test prevented. A song is already playing."] = "Song test prevented. A song is already playing."
	L["Song test prevented. BloodlustMusic is currently muted."] = "Song test prevented. BloodlustMusic is currently muted."
	L["Song test prevented. Please fill in all the details."] = "Song test prevented. Please fill in all the details."
	L["Song test prevented. The song is not enabled."] = "Song test prevented. The song is not enabled."
	L["Sound Channel"] = "Sound Channel"
	L["Sound not reset properly after Hero? Try setting your in-game volume at Main Menu -> System -> Sound to your preferred normal level, then click the button below."] = "Sound not reset properly after Hero? Try setting your in-game volume at Main Menu -> System -> Sound to your preferred normal level, then click the button below."
	L["Sound Reset"] = "Sound Reset"
	L["Soundchannel changed to: "] = "Soundchannel changed to: "
	L["Test song stopped"] = "Test song stopped"
	L["Test"] = "Test"
	L["Testing Friends"] = "Testing Friends"
	L["Testing Input"] = "Testing Input"
	L["The addon is now muted, no songs will play."] = "The addon is now muted, no songs will play."
	L["The addon is now unmuted, enjoy the songs :)"] = "The addon is now unmuted, enjoy the songs :)"
	L["This will set this song back to its default, hard-coded values. \n \n \n|cFFFFD100'"] = "This will set this song back to its default, hard-coded values. \n \n \n|cFFFFD100'"
	L["Use the Dropdown menu below to set what soundchannel you want Hero to play on. Unsure? Dialog is recommended, Master is more fun."] = "Use the Dropdown menu below to set what soundchannel you want Hero to play on. Unsure? Dialog is recommended, Master is more fun."
	L["Use the Slider menu below to set how loud the music during Hero should be. Don't want the volume raised? Enter a number lower or equal to your current volume for your soundchannel. You can view this under Main menu -> System -> Sound."] = "Use the Slider menu below to set how loud the music during Hero should be. Don't want the volume raised? Enter a number lower or equal to your current volume for your soundchannel. You can view this under Main menu -> System -> Sound."
	L["Volume of "] = "Volume of "
	L["Want to customise what songs you hear? Below you can tick the boxes to turn individual songs on or off. You can press the edit button to change the names and change the song file itself. This way you can introduce your own custom songs without digging in the code.\n \nMessed up? Each edit button has a default button. Messed up a lot? At the bottom you'll see a button to put all songs back to their hard-coded values.\n\nFor more info on the whole process, please visit the addon site."] = "Want to customise what songs you hear? Below you can tick the boxes to turn individual songs on or off. You can press the edit button to change the names and change the song file itself. This way you can introduce your own custom songs without digging in the code.\n \nMessed up? Each edit button has a default button. Messed up a lot? At the bottom you'll see a button to put all songs back to their hard-coded values.\n\nFor more info on the whole process, please visit the addon site."
	L["Want to hear a certain song when a certain player casts Hero? You can by using the Favored Friend feature below. Just click the edit button and enter some values in the screen that pops up. You'll need the name of your friend, the title of the song, and the filename. The song can be either a song in the default list or a custom one, following the same rules for custom songs as above. More info on the addon page."] = "Want to hear a certain song when a certain player casts Hero? You can by using the Favored Friend feature below. Just click the edit button and enter some values in the screen that pops up. You'll need the name of your friend, the title of the song, and the filename. The song can be either a song in the default list or a custom one, following the same rules for custom songs as above. More info on the addon page."
	L["\n \nPending changes: \n \n|cFFFFD100'"] = "\n \nPending changes: \n \n|cFFFFD100'"
	L["\n \nThis will set this song back to its default, hard-coded values. \n \n|cFFFFD100'"] = "\n \nThis will set this song back to its default, hard-coded values. \n \n|cFFFFD100'"
	L["\n |cFFFFD100WARNING:|r This will clear the entire list of Favored Friends and all checkboxes will be turned OFF.\n \n \n This action cannot be reversed and any change you have made to this list will have to be entered manually again. \n \n \n Accept and reload?"] = "\n |cFFFFD100WARNING:|r This will clear the entire list of Favored Friends and all checkboxes will be turned OFF.\n \n \n This action cannot be reversed and any change you have made to this list will have to be entered manually again. \n \n \n Accept and reload?"
	L["\n |cFFFFD100WARNING:|r This will set all songs back to their default, hard-coded values, even your custom songs. \n \n \n This action cannot be reversed and any change you have made to any song will have to be entered manually again. \n \n \n Accept and reload?"] = "\n |cFFFFD100WARNING:|r This will set all songs back to their default, hard-coded values, even your custom songs. \n \n \n This action cannot be reversed and any change you have made to any song will have to be entered manually again. \n \n \n Accept and reload?"

	--BloodlustMusic.lua
	L[" volume channel is muted."] = " volume channel is muted."
	L[". But the song wasn't enabled. Playing another song instead."] = ". But the song wasn't enabled. Playing another song instead."
	L["A song is already playing."] = "A song is already playing."
	L["Ambience"] = "Ambience"
	L["Dialog"] = "Dialog"
	L["Hero was cast by your Favored Friend: "] = "Hero was cast by your Favored Friend: "
	L["Master"] = "Master"
	L["Music"] = "Music"
	L["No song was selected. BloodlustMusic is currently muted."] = "No song was selected. BloodlustMusic is currently muted."
	L["No song was selected. The Addon can't find any songs, you've disabled too many or your computer's sound is muted. I think? idk man."] = "No song was selected. The Addon can't find any songs, you've disabled too many or your computer's sound is muted. I think? idk man."
	L["No song was selected. Your "] = "No song was selected. Your "
	L["No song was selected. Your WoW sound is muted."] = "No song was selected. Your WoW sound is muted."
	L["Now Playing: "] = "Now Playing: "
	L["SFX"] = "SFX"
	L["Song Stopped"] = "Song Stopped"
	L["|cFFff2f00BloodlustMusic:|r "] = "|cFFff2f00BloodlustMusic:|r "

return end

if LOCALE == "zhCN" then
	L[" is now set to: "] = " 现在设置为："
	L[" soundchannel during Hero"] = " 英勇期间的声道"
	L[" volume during Hero"] = " 英勇期间的音量"
	L["'|r will play: "] = "'|r 播放: "
	L["'|r\n becomes \n|cFFFFD100'"] = "'|r\n 改为 \n|cFFFFD100'"
	L["'|r\n turns back to \n|cFFFFD100'"] = "'|r\n 改回到 \n|cFFFFD100'"
	L["'|r\n \n \n Accept and reload?"] = "'|r\n \n \n 接受并重新加载？"
	L["A stupid Addon to play music during Hero, Bloodlust, Primal Rage, etc. You can change a couple of settings below to your liking. Some barebones information is provided next to the corresponding option. For a more in depth explanation, please refer to the description of the addon at: https://www.curseforge.com/wow/addons/bloodlustmusic . Thanks and enjoy!"] = "在获得英勇/嗜血/远古狂乱/青铜龙的祝福等增益在游戏中播放音乐的傻瓜式插件。你可以根据自己的喜好更改下面的一些设置。相应选项旁边会提供一些基本信息。如需更深入的解释，请参阅插件说明：https://www.curseforge.com/wow/addons/bloodlustmusic 。谢谢，祝你玩得愉快！"
	L["Accept"] = "接受"
	L["Bloodlust Music"] = "英勇音乐"
	L["Cancel"] = "取消"
	L["Change Song filename to: \n |cFFFFD100(NB: Needs filetype in the name, .ogg is most common. Also make sure the file for any custom song is in the 'customsongs' folder, not the 'sounds' folder)|r"] = "将歌曲文件名改为：\n |cFFFFD100（注意：文件名中需要包含文件类型，.ogg 是最常见的。确保任何自定义歌曲的文件在 'customsongs' 文件夹中，而不是 'sounds' 文件夹）|r"
	L["Change Title to: "] = "标题改为："
	L["Changing soundchannel prevented, please do so after hero has ended"] = "无法更改声道，请在增益结束后再进行"
	L["Clear Favored Friend List"] = "清除挚友设置列表"
	L["Current soundchannel: "] = "当前声道："
	L["Edit"] = "编辑"
	L["Everything set? Press the button below for a 10 second test song. Enter a number between 1 and 60 to test a specific song. Want a random one? Leave it empty or place a 0. Please note: no other songs can play at the same time."] = "一切设置好了吗？按下面的按钮播放 10 秒的测试歌曲。输入 1 到 60 之间的数字以测试特定的歌曲。想要随机歌曲？留空或输入 0。请注意：不能同时播放其他歌曲。"
	L["Favored Friend filename: \n |cFFFFD100(NB: Needs filetype in the name, .ogg is most common. Also make sure the file for any custom song is in the 'customsongs' folder, not the 'sounds' folder)|r"] = "挚友文件名：\n |cFFFFD100（注意：文件名中需要包含文件类型，.ogg 是最常见的。确保任何自定义歌曲的文件在 'customsongs' 文件夹中，而不是 'sounds' 文件夹）|r"
	L["Favored Friend Name: "] = "挚友姓名："
	L["Favored Friend Song Title: "] = "挚友歌曲标题："
	L["|cFFFFD100Mute|r"] = "|cFFFFD100静音|r"
	L["Pending changes: \n \n \n|cFFFFD100'"] = "待处理更改：\n \n \n|cFFFFD100'"
	L["Play a test song"] = "播放测试歌曲"
	L["Regular volume level for "] = "常规音量级别为 "
	L["Reset to Default"] = "重置为默认"
	L["Resetting prevented, please try again after Hero has ended"] = "重置被阻止，请在英勇结束后重试"
	L["Set all songs to default"] = "将所有歌曲设置为默认"
	L["Set Max number of soundchannels during Hero to 128?"] = "将英勇期间的最大声音通道数设置为 128？"
	L["Sometimes the music will cut out if stuff gets too busy. You can try to prevent this by checking the box below. This will make sure WoW can play more sounds at the same time, by upping the number of allowed soundchannels. Afterwards it will put it back to normal levels. Highly recommended to check the addon description for more info."] = "有时如果事情变得太忙，音乐会中断。你可以尝试通过勾选下面的框来防止这种情况。这将确保 WoW 可以同时播放更多声音，通过增加允许的声音通道数量。之后，它会恢复到正常水平。强烈建议查看插件描述以获取更多信息。"
	L["Song test prevented. A song is already playing."] = "歌曲测试被阻止。已有一首歌曲正在播放。"
	L["Song test prevented. BloodlustMusic is currently muted."] = "歌曲测试被阻止。BloodlustMusic 当前已静音。"
	L["Song test prevented. Please fill in all the details."] = "歌曲测试被阻止。请填写所有详细信息。"
	L["Song test prevented. The song is not enabled."] = "歌曲测试被阻止。该歌曲未启用。"
	L["Sound Channel"] = "声音通道"
	L["Sound not reset properly after Hero? Try setting your in-game volume at Main Menu -> System -> Sound to your preferred normal level, then click the button below."] = "英勇结束后声音未正确重置？尝试在主菜单 -> 系统 -> 声音中将游戏内音量设置为你喜欢的正常水平，然后点击下面的按钮。"
	L["Sound Reset"] = "声音重置"
	L["Soundchannel changed to: "] = "声道改为："
	L["Test song stopped"] = "测试歌曲停止"
	L["Test"] = "测试"
	L["Testing Friends"] = "测试挚友"
	L["Testing Input"] = "测试输入信息"
	L["The addon is now muted, no songs will play."] = "插件现在已静音，无法播放任何歌曲。"
	L["The addon is now unmuted, enjoy the songs :)"] = "插件现在已取消静音，享受音乐吧 :)"
	L["This will set this song back to its default, hard-coded values. \n \n \n|cFFFFD100'"] = "这将把这首歌恢复到其默认的硬编码值。\n \n \n|cFFFFD100'"
	L["Use the Dropdown menu below to set what soundchannel you want Hero to play on. Unsure? Dialog is recommended, Master is more fun."] = "使用下面的下拉菜单设置你希望英勇在哪个声音通道播放。 unsure? 推荐使用对话，主音道更有趣。"
	L["Use the Slider menu below to set how loud the music during Hero should be. Don't want the volume raised? Enter a number lower or equal to your current volume for your soundchannel. You can view this under Main menu -> System -> Sound."] = "使用下面的滑块菜单设置英勇期间音乐的音量。如果不想提高音量？输入一个低于或等于你当前声音通道音量的数字。你可以在主菜单 -> 系统 -> 声音中查看。"
	L["Volume of "] = "音量为 "
	L["Want to customise what songs you hear? Below you can tick the boxes to turn individual songs on or off. You can press the edit button to change the names and change the song file itself. This way you can introduce your own custom songs without digging in the code.\n \nMessed up? Each edit button has a default button. Messed up a lot? At the bottom you'll see a button to put all songs back to their hard-coded values.\n\nFor more info on the whole process, please visit the addon site."] = "想要自定义你听到的歌曲吗？在下面你可以勾选框来打开或关闭单独的歌曲。你可以按编辑按钮更改名称和歌曲文件本身。这样你可以引入自己的自定义歌曲，而无需深入代码。\n \n搞砸了？每个编辑按钮都有一个默认按钮。搞砸得很严重？在底部你会看到一个按钮，可以将所有歌曲恢复到其硬编码值。\n\n有关整个过程的更多信息，请访问插件网站。"
	L["Want to hear a certain song when a certain player casts Hero? You can by using the Favored Friend feature below. Just click the edit button and enter some values in the screen that pops up. You'll need the name of your friend, the title of the song, and the filename. The song can be either a song in the default list or a custom one, following the same rules for custom songs as above. More info on the addon page."] = "想在某个玩家施放英勇时听到特定的歌曲吗？你可以使用下面的挚友功能。只需点击编辑按钮并在弹出的屏幕中输入一些值。你需要你朋友的姓名、歌曲的标题和文件名。歌曲可以是默认列表中的歌曲或自定义歌曲，遵循上述自定义歌曲的相同规则。有关更多信息，请访问插件页面。"
	L["\n \nPending changes: \n \n|cFFFFD100'"] = "\n \n待处理更改：\n \n|cFFFFD100'"
	L["\n \nThis will set this song back to its default, hard-coded values. \n \n|cFFFFD100'"] = "\n \n这将把这首歌恢复到其默认的硬编码值。\n \n|cFFFFD100'"
	L["\n |cFFFFD100WARNING:|r This will clear the entire list of Favored Friends and all checkboxes will be turned OFF.\n \n \n This action cannot be reversed and any change you have made to this list will have to be entered manually again. \n \n \n Accept and reload?"] = "\n |cFFFFD100WARNING:|r 这将清除整个挚友列表，所有复选框将被关闭。\n \n \n 此操作无法撤销，您对该列表所做的任何更改都必须手动重新输入。\n \n \n 接受并重新加载？"
	L["\n |cFFFFD100WARNING:|r This will set all songs back to their default, hard-coded values, even your custom songs. \n \n \n This action cannot be reversed and any change you have made to any song will have to be entered manually again. \n \n \n Accept and reload?"] = "\n |cFFFFD100WARNING:|r 这将把所有歌曲恢复到其默认的硬编码值，包括您自定义的歌曲。\n \n \n 此操作无法撤销，您对任何歌曲所做的任何更改都必须手动重新输入。\n \n \n 接受并重新加载？"

	--BloodlustMusic.lua
	L[" volume channel is muted."] = " 音量通道已静音。"
	L[". But the song wasn't enabled. Playing another song instead."] = "。但这首歌未启用。改为播放另一首歌。"
	L["A song is already playing."] = "已有一首歌曲正在播放。"
	L["Ambience"] = "环境音"
	L["Dialog"] = "对话"
	L["Hero was cast by your Favored Friend: "] = "英勇由你的挚友施放："
	L["Master"] = "主音道"
	L["Music"] = "音乐"
	L["No song was selected. BloodlustMusic is currently muted."] = "未选择任何歌曲。BloodlustMusic 当前已静音。"
	L["No song was selected. The Addon can't find any songs, you've disabled too many or your computer's sound is muted. I think? idk man."] = "未选择任何歌曲。插件无法找到任何歌曲，你禁用的太多，或者你的电脑声音已静音。我想？我不知道。"
	L["No song was selected. Your "] = "未选择任何歌曲。你的 "
	L["No song was selected. Your WoW sound is muted."] = "未选择任何歌曲。你的 WoW 声音已静音。"
	L["Now Playing: "] = "正在播放："
	L["SFX"] = "音效"
	L["Song Stopped"] = "歌曲停止"
	L["|cFFff2f00BloodlustMusic:|r "] = "|cFFff2f00BloodlustMusic:|r "

return end

